paths:
  /samples:
    get:
      tags:
        - Samples
      summary: Get all samples
      responses:
        200:
          description: 'OK'
        500:
          description: 'Internal Server Error'