# definitions
definitions:
  sample:
    type: object
    required:
        - title
    properties:
      title:
        type: string
      description:
        type: string

# Paths
paths:
  /samples:
    # [GET] /samples
    get:
      tags:
        - Samples
      summary: Get all samples
      responses:
        200:
          description: 'OK'
        500:
          description: 'Internal Server Error'
    # [POST] /samples
    post:
      tags:
        - Samples
      summary: Create new sample
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/sample'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /samples/{id}:
    # [GET] /samples/:id
    get:
      tags:
        - Samples
      summary: Get sample by ID
      parameters:
        - name: id
          in: path
          required: true
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not Found'
        500:
          description: 'Internal Server Error'
    put:
      tags:
        - Samples
      summary: Update sample
      parameters:
      - name: id
        in: path
        required: true
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/sample'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'