### Variables
@baseUrl = http://localhost:4000

### Get all samples
GET {{ baseUrl }}/samples
Content-Type: application/json

### Get sample by ID
GET {{ baseUrl }}/samples/67b0c4c42d75948ca43b095e
Content-Type:  application/application/json

### Create sample
POST {{ baseUrl }}/samples
Content-Type: application/json

{
  "title": "title http documentation",
  "description": "description http documentation"
}

### Update sample by ID
PUT {{ baseUrl }}/samples/67b0c5d968f4300df0e09b2b
Content-Type: application/json

{
  "title": "title http documentation edited",
  "description": "description http documentation edited"
}

### Hard delete sample by ID
DELETE {{ baseUrl }}/samples/67b0c5d968f4300df0e09b2b/hard
Content-Type: application/json